import { TokenProposal } from '../pipeline/decision';
import { generateTokensFile } from '../pipeline';

export interface PrimitiveSource {
  // Generated file name → file content. Empty when no tokens were proposed.
  files: Record<string, string>;
}

const FILE_HEADER = `// Auto-generated by remediation
// Run \`remediation primitives\` to regenerate
//
// A constrained React API compiled from the detected design tokens. Every
// visual prop accepts token names only — values outside the design system
// (e.g. <Box padding="17px" />) fail to typecheck, so the compiler, not an
// extra lint rule, keeps generated UI on-system.
`;

// Compile the token proposals into a typed React primitives API (tokens +
// Box/Text). Props are keyed to token names, so the union types are what keep
// generated code on-system: there is no legal way to pass a bare value.
export function generatePrimitives(
  proposals: TokenProposal[],
  opts: { tokensImport?: string } = {}
): PrimitiveSource {
  const hasColors = proposals.some(p => p.cluster.type === 'color');
  const hasSpacing = proposals.some(p => p.cluster.type === 'spacing');
  const hasTypography = proposals.some(p => p.cluster.type === 'typography');

  if (!hasColors && !hasSpacing && !hasTypography) {
    return { files: {} };
  }

  const source = opts.tokensImport ?? './tokens';
  const files: Record<string, string> = {};

  // When the project already declares a tokens module (config `tokensImport`),
  // point the primitives at it and skip writing a local tokens file.
  if (!opts.tokensImport) {
    files['tokens.ts'] = generateTokensFile(proposals);
  }

  files['primitives.tsx'] = buildPrimitives(hasColors, hasSpacing, hasTypography, source);

  return { files };
}

function buildPrimitives(
  hasColors: boolean,
  hasSpacing: boolean,
  hasTypography: boolean,
  source: string
): string {
  const imported = [
    hasColors && 'colors',
    hasSpacing && 'spacing',
    hasTypography && 'typography',
  ].filter(Boolean) as string[];

  const parts: string[] = [
    FILE_HEADER,
    `import * as React from 'react';`,
    `import { ${imported.join(', ')} } from '${source}';`,
    '',
    hasColors && 'export type ColorName = keyof typeof colors;',
    hasSpacing && 'export type Spacing = keyof typeof spacing;',
    hasTypography && 'export type TypeScale = keyof typeof typography;',
    '',
  ].filter((line): line is string => line !== false);

  if (hasSpacing) {
    parts.push(
      ...SPACING_RESOLVER.split('\n'),
      ''
    );
  }

  if (hasSpacing || hasColors) {
    parts.push(boxSource(hasColors, hasSpacing), '');
  }

  if (hasColors || hasTypography) {
    parts.push(textSource(hasColors, hasTypography), '');
  }

  return parts.join('\n').replace(/\n+$/, '') + '\n';
}

const SPACING_RESOLVER = `function resolveSpacing(
  value: Spacing | [Spacing, Spacing] | [Spacing, Spacing, Spacing, Spacing] | undefined
): string | undefined {
  if (value === undefined) return undefined;
  if (Array.isArray(value)) return value.map((v) => spacing[v]).join(' ');
  return spacing[value];
}`;

function boxSource(hasColors: boolean, hasSpacing: boolean): string {
  const props: string[] = ['  as?: React.ElementType;'];
  if (hasSpacing) {
    props.push(
      '  padding?: Spacing | [Spacing, Spacing] | [Spacing, Spacing, Spacing, Spacing];',
      '  margin?: Spacing | [Spacing, Spacing] | [Spacing, Spacing, Spacing, Spacing];',
      '  gap?: Spacing;'
    );
  }
  if (hasColors) {
    props.push('  backgroundColor?: ColorName;', '  borderColor?: ColorName;');
  }

  const destructured = [
    "as: Tag = 'div'",
    hasSpacing && 'padding',
    hasSpacing && 'margin',
    hasSpacing && 'gap',
    hasColors && 'backgroundColor',
    hasColors && 'borderColor',
    'style',
    'children',
    '...rest',
  ].filter(Boolean) as string[];

  const params = destructured.map(line => `  ${line}`).join(',\n');

  const styleEntries: string[] = [];
  if (hasSpacing) {
    styleEntries.push(
      '    ...(padding !== undefined && { padding: resolveSpacing(padding) }),',
      '    ...(margin !== undefined && { margin: resolveSpacing(margin) }),',
      '    ...(gap !== undefined && { gap: spacing[gap] }),'
    );
  }
  if (hasColors) {
    styleEntries.push(
      '    ...(backgroundColor !== undefined && { backgroundColor: colors[backgroundColor] }),',
      '    ...(borderColor !== undefined && { borderColor: colors[borderColor] }),'
    );
  }

  return `export type BoxProps = {
${props.join('\n')}
} & React.HTMLAttributes<HTMLElement>;

export function Box({
${params}
}: BoxProps) {
  const resolved: React.CSSProperties = {
${styleEntries.join('\n')}
  };
  return (
    <Tag {...rest} style={{ ...style, ...resolved }}>
      {children}
    </Tag>
  );
}`;
}

function textSource(hasColors: boolean, hasTypography: boolean): string {
  const props: string[] = ['  as?: React.ElementType;'];
  if (hasColors) props.push('  color?: ColorName;');
  if (hasTypography) {
    props.push('  fontSize?: TypeScale;', '  fontWeight?: TypeScale;');
  }

  const destructured = [
    "as: Tag = 'p'",
    hasColors && 'color',
    hasTypography && 'fontSize',
    hasTypography && 'fontWeight',
    'style',
    'children',
    '...rest',
  ].filter(Boolean) as string[];

  const params = destructured.map(line => `  ${line}`).join(',\n');

  const styleEntries: string[] = [];
  if (hasColors) styleEntries.push('    ...(color !== undefined && { color: colors[color] }),');
  if (hasTypography) {
    styleEntries.push(
      '    ...(fontSize !== undefined && { fontSize: typography[fontSize] }),',
      '    ...(fontWeight !== undefined && { fontWeight: typography[fontWeight] }),'
    );
  }

  return `export type TextProps = {
${props.join('\n')}
} & React.HTMLAttributes<HTMLElement>;

export function Text({
${params}
}: TextProps) {
  const resolved: React.CSSProperties = {
${styleEntries.join('\n')}
  };
  return (
    <Tag {...rest} style={{ ...style, ...resolved }}>
      {children}
    </Tag>
  );
}`;
}