import { TokenProposal, DecisionResult } from './decision';

// Emits a DESIGN.md in the @google/design.md format
// (https://github.com/google-labs-code/design.md): YAML frontmatter with
// machine-readable design tokens + a markdown body with human-readable prose
// sections, in the spec's canonical section order. The prose derives concrete,
// actionable guidance from the detected values rather than describing the tool
// or the detection process.
export function generateDesignMd(decision: DecisionResult, projectPath?: string): string {
  const colorTokens = decision.proposals.filter(p => p.cluster.type === 'color');
  const spacingTokens = decision.proposals.filter(p => p.cluster.type === 'spacing');
  const typographyTokens = decision.proposals.filter(p => p.cluster.type === 'typography');

  if (colorTokens.length === 0 && spacingTokens.length === 0 && typographyTokens.length === 0) {
    return 'No design tokens detected. Run `remediation analyze` to inspect your codebase.';
  }

  const byFreq = (a: TokenProposal, b: TokenProposal) => b.frequency - a.frequency;
  const mostUsedColor = [...colorTokens].sort(byFreq)[0];
  const mostUsedSpacing = [...spacingTokens].sort(byFreq)[0];

  const lines: string[] = [];

  lines.push('---');
  lines.push('version: alpha');
  lines.push('name: ' + yamlQuote(projectName(projectPath)));
  lines.push(`description: ${yamlQuote(description(decision, colorTokens, spacingTokens, typographyTokens))}`);
  lines.push('');
  lines.push(yamlTokens(colorTokens, spacingTokens, typographyTokens));
  lines.push('---');
  lines.push('');

  lines.push('# Design System');
  lines.push('');
  lines.push('> Auto-generated by [remediation](https://github.com/arnaudmanaranche/remediation).');
  lines.push('> Run `remediation design` to regenerate.');
  lines.push('');

  // Overview
  lines.push('## Overview');
  lines.push('');
  lines.push(`This design system for **${projectName(projectPath)}** was derived from the values that`);
  lines.push(`appear most consistently across the codebase (${decision.summary.totalValues} design values in`);
  lines.push(`${decision.summary.totalClusters} clusters). It prioritizes the tokens that recur most`);
  lines.push('often, so generated UI blends with what already exists. When a visual decision is not');
  lines.push('covered here, follow the Do\'s and Don\'ts at the end of this document.');

  // Colors
  lines.push('');
  lines.push('## Colors');
  lines.push('');
  if (colorTokens.length > 0) {
    lines.push(`The most frequently used color is **\`${displayNameOf(mostUsedColor!)}\`** (${mostUsedColor!.cluster.canonical}).`);
    lines.push('Use it as the anchor for foreground text and interactive emphasis, and treat the');
    lines.push('remaining colors as supporting surfaces, borders, and secondary text. Do not introduce');
    lines.push('a new color when one of these already fits.');
  } else {
    lines.push('No color tokens were detected.');
  }

  // Typography
  lines.push('');
  lines.push('## Typography');
  lines.push('');
  if (typographyTokens.length > 0) {
    const sizes = typographyTokens.filter(t => /(?:px|rem|em)$/.test(t.cluster.canonical));
    const weights = typographyTokens.filter(t => !/(?:px|rem|em)$/.test(t.cluster.canonical));
    lines.push(`A font family was not detected — adopt the project\'s UI font and apply these detected`);
    lines.push('type roles to it. Keep font sizes to the detected levels below and do not invent');
    lines.push('ad-hoc sizes or weights outside this scale.');
    if (sizes.length > 0) {
      lines.push('');
      lines.push(`${labelTokenCount(sizes.length, 'size level')} detected: ${listCode(sizes.map(s => displayNameOf(s)))}.`);
    }
    if (weights.length > 0) {
      lines.push(`Weight${weights.length === 1 ? '' : 's'} detected: ${listCode(weights.map(w => displayNameOf(w)))} — use the heavier weights sparingly for emphasis.`);
    }
  } else {
    lines.push('No typography tokens were detected.');
  }

  // Layout
  lines.push('');
  lines.push('## Layout');
  lines.push('');
  if (spacingTokens.length > 0) {
    lines.push(`The dominant spacing unit is **\`${displayNameOf(mostUsedSpacing!)}\`** (${mostUsedSpacing!.cluster.canonical}).`);
    lines.push('Build margins, padding, and gaps from this scale rather than inventing new distances;');
    lines.push('use larger detected steps for section-level rhythm and the smaller ones for');
    lines.push('micro-adjustments.');
  } else {
    lines.push('No spacing tokens were detected.');
  }

  // Elevation & Depth
  lines.push('');
  lines.push('## Elevation & Depth');
  lines.push('');
  lines.push('Confirm actual shadow usage and document it here (e.g. the exact spread, blur, and color');
  lines.push('of each elevation level, or an explicit flat-design choice). Prefer depth conveyed through');
  lines.push('the color and spacing tokens above over ad-hoc shadows.');

  // Shapes
  lines.push('');
  lines.push('## Shapes');
  lines.push('');
  lines.push('Confirm actual corner-radius usage and document it here (e.g. `sm: 4px`, `md: 8px`,');
  lines.push('`full: 9999px`). Keep radii consistent across equivalents — do not mix sharp and rounded');
  lines.push('corners within the same view without a reason.');

  // Do's and Don'ts
  lines.push('');
  lines.push('## Do\'s and Don\'ts');
  lines.push('');
  lines.push('These rules generalize from the detected design system:');
  lines.push('');
  if (colorTokens.length > 0) {
    lines.push(`- Do reuse **\`${displayNameOf(mostUsedColor!)}\`** for the single most important action or emphasis per view`);
    lines.push(`- Do use the supporting colors (${listCode(colorTokens.slice(0, 3).map(c => displayNameOf(c)))}) for surfaces, borders, and secondary text`);
    lines.push('- Don\'t introduce a color that is not in the palette above');
    lines.push('- Don\'t rely on color alone to convey meaning — pair it with a non-color cue');
  }
  if (spacingTokens.length > 0) {
    lines.push(`- Do scale spacing from **\`${displayNameOf(mostUsedSpacing!)}\`** (${mostUsedSpacing!.cluster.canonical})`);
    lines.push('- Don\'t invent fractional or arbitrary spacing between the detected steps');
  }
  if (typographyTokens.length > 0) {
    lines.push('- Do keep font sizes and weights within the detected type scale');
    lines.push('- Don\'t use more than one or two weights on a single screen');
  }
  lines.push('- Don\'t add shadows, gradients, or effects that are not documented in this file');

  return lines.join('\n');
}

function yamlTokens(
  colorTokens: TokenProposal[],
  spacingTokens: TokenProposal[],
  typographyTokens: TokenProposal[]
): string {
  const sections: string[] = [];

  if (colorTokens.length > 0) {
    sections.push('colors:');
    for (const proposal of colorTokens) {
      sections.push(`  ${yamlKey(namedKey(proposal.tokenRef, proposal.tokenName))}: ${yamlQuote(proposal.cluster.canonical)}`);
    }
  }

  if (spacingTokens.length > 0) {
    sections.push('spacing:');
    for (const proposal of spacingTokens) {
      sections.push(`  ${yamlKey(namedKey(proposal.tokenRef, proposal.tokenName))}: ${yamlQuote(proposal.cluster.canonical)}`);
    }
  }

  if (typographyTokens.length > 0) {
    sections.push('typography:');
    for (const proposal of typographyTokens) {
      sections.push(`  ${yamlKey(namedKey(proposal.tokenRef, proposal.tokenName))}:`);
      const props = typographyProps(proposal.cluster.canonical);
      for (const [k, v] of props) {
        sections.push(`    ${k}: ${v}`);
      }
    }
  }

  return sections.join('\n');
}

// A token reference like `colors.primary` names both the group and the key;
// inside the `colors:` map the key is just the trailing part (`primary`).
function namedKey(tokenRef: string | undefined, fallback: string): string {
  const fromRef = displayName(tokenRef);
  return fromRef !== '' ? fromRef : fallback;
}

// Strip the group prefix (``colors.``) off a token reference, so
// ``colors.primary`` → ``primary``. Bare names (no dot) pass through unchanged.
function displayName(tokenRef: string | undefined): string {
  if (!tokenRef) return '';
  const dot = tokenRef.indexOf('.');
  if (dot === -1) return tokenRef;
  const name = tokenRef.slice(dot + 1);
  return name === '' ? tokenRef : name;
}

function displayNameOf(proposal: TokenProposal): string {
  return namedKey(proposal.tokenRef, proposal.tokenName);
}

// Map a typography canonical ('14px', '600', 'semibold') to its schema object
// properties. Only fontSize / fontWeight are detected; family, lineHeight, and
// letterSpacing are intentionally left for the user to fill in.
function typographyProps(canonical: string): Array<[string, string]> {
  const sizeMatch = canonical.match(/^(\d+(?:\.\d+)?)(px|rem|em)$/);
  if (sizeMatch) return [['fontSize', `${sizeMatch[1]}${sizeMatch[2]}`]];

  const asNum = parseInt(canonical, 10);
  if (!isNaN(asNum)) return [['fontWeight', String(asNum)]];

  return [['fontWeight', canonical]];
}

function projectName(projectPath?: string): string {
  if (!projectPath || projectPath === '.') return 'Project';
  return projectPath.replace(/[\\/]+$/, '');
}

function description(
  decision: DecisionResult,
  colorTokens: TokenProposal[],
  spacingTokens: TokenProposal[],
  typographyTokens: TokenProposal[]
): string {
  const parts: string[] = [];
  if (colorTokens.length > 0) parts.push(`${colorTokens.length} colors`);
  if (spacingTokens.length > 0) parts.push(`${spacingTokens.length} spacing steps`);
  if (typographyTokens.length > 0) parts.push(`${typographyTokens.length} typography levels`);
  return `Design system derived from ${decision.summary.totalValues} detected values (${parts.join(', ')}).`;
}

function labelTokenCount(count: number, noun: string): string {
  return `${count} ${noun}${count === 1 ? '' : 's'}`;
}

function listCode(values: string[]): string {
  const joined = values.map(v => `\`${v}\``);
  if (joined.length === 1) return joined[0];
  return joined.slice(0, -1).join(', ') + ' and ' + joined[joined.length - 1];
}

// Quote a YAML scalar that could contain special characters. Token hex/dim
// values are simple enough to emit bare, but names/descriptions need quoting.
function yamlQuote(value: string): string {
  return JSON.stringify(value);
}

// A YAML map key: keys here are generated identifiers or config refs, which are
// plain strings, so emit bare (no quotes needed unless they contain ':').
function yamlKey(key: string): string {
  return key.includes(':') ? JSON.stringify(key) : key;
}
