import { extractFromProject, ExtractedValue } from './extractor';
import { normalizeAll, NormalizedValue } from './normalizer';
import { clusterValues, getSuggestedNames, Cluster } from './clusterer';
import { decideTokens, DecisionResult, TokenProposal } from './decision';

export interface PipelineResult {
  extraction: ExtractedValue[];
  normalization: NormalizedValue[];
  clustering: Cluster[];
  decision: DecisionResult;
}

export function runPipeline(projectPath: string): PipelineResult {
  const extraction = extractFromProject(projectPath);
  const normalization = normalizeAll(extraction);
  const clustering = clusterValues(normalization);
  const suggestedNames = getSuggestedNames(clustering);
  const decision = decideTokens(clustering, suggestedNames);

  return {
    extraction,
    normalization,
    clustering,
    decision,
  };
}

export function generateTokensFile(proposals: TokenProposal[]): string {
  const lines: string[] = [];

  lines.push('// Auto-generated by remediation');
  lines.push('// Run `remediation analyze` to regenerate');
  lines.push('');

  const colorTokens = proposals.filter(p => p.cluster.type === 'color');
  const spacingTokens = proposals.filter(p => p.cluster.type === 'spacing');
  const typographyTokens = proposals.filter(p => p.cluster.type === 'typography');

  if (colorTokens.length > 0) {
    lines.push('export const colors = {');
    for (const proposal of colorTokens) {
      lines.push(`  '${proposal.tokenName}': '${proposal.cluster.canonical}',`);
    }
    lines.push('};');
    lines.push('');
  }

  if (spacingTokens.length > 0) {
    lines.push('export const spacing = {');
    for (const proposal of spacingTokens) {
      lines.push(`  '${proposal.tokenName}': '${proposal.cluster.canonical}',`);
    }
    lines.push('};');
    lines.push('');
  }

  if (typographyTokens.length > 0) {
    lines.push('export const typography = {');
    for (const proposal of typographyTokens) {
      lines.push(`  '${proposal.tokenName}': '${proposal.cluster.canonical}',`);
    }
    lines.push('};');
    lines.push('');
  }

  lines.push('export const tokens = {');
  if (colorTokens.length > 0) lines.push('  colors,');
  if (spacingTokens.length > 0) lines.push('  spacing,');
  if (typographyTokens.length > 0) lines.push('  typography,');
  lines.push('};');
  lines.push('');

  return lines.join('\n');
}
