import { TokenProposal } from '../pipeline/decision';
import { toCanonical } from '../pipeline/normalizer';
import { splitValueTokens } from '../pipeline/valueTokenizer';
import { compilePrimitives } from '../primitives/compiler';
import { DetectedComponent } from './detector';
import { COLOR_PROPS, SPACING_PROPS } from '../ast/cssProperties';

export interface ComponentsResult {
  files: Record<string, string>;
  report: ComponentReportItem[];
}

export type ComponentReportItem =
  | { type: 'emitted'; component: string }
  | { type: 'merged'; component: string; into: string }
  | { type: 'unmapped'; component: string; values: string[] };

export interface ComponentCompilerOptions {
  tokensImport?: string;
}

const FILE_HEADER = `// Auto-generated by remediation
// Run \`remediation components\` to regenerate
//
// A token-constrained component library: every component found in the
// codebase, re-emitted with props typed to token names only (imported from
// ./primitives), so off-system values (e.g. <Card margin="13px" />) fail to
// typecheck. Style values that don't resolve to a token stay as literal LOOK.
`;

type SlotKind = 'color' | 'spacing' | 'fontSize' | 'fontWeight' | null;

interface Unit {
  name: string;
  element: string;
  rootAttrs: Record<string, string>;
  voidElement: boolean;
  childrenSource: string | null;
  defaults: Record<string, string | string[]>;
  look: Record<string, string | number>;
  unmapped: string[];
}

interface Available {
  color: boolean;
  spacing: boolean;
  fontSize: boolean;
  fontWeight: boolean;
}

const SPACING_TUPLE_TYPE =
  'Spacing | [Spacing, Spacing] | [Spacing, Spacing, Spacing] | [Spacing, Spacing, Spacing, Spacing]';

const VOID_ELEMENTS = new Set([
  'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'link', 'meta', 'param', 'source', 'track', 'wbr',
]);

export function compileComponents(
  proposals: TokenProposal[],
  detected: DetectedComponent[],
  opts: ComponentCompilerOptions = {}
): ComponentsResult {
  const primitives = compilePrimitives(proposals, { tokensImport: opts.tokensImport });
  if (Object.keys(primitives.files).length === 0) {
    return { files: {}, report: [] };
  }

  const maps = buildTokenMaps(proposals);
  const available = {
    color: maps.colors.size > 0,
    spacing: maps.spacing.size > 0,
    fontSize: maps.typographySizes.size > 0,
    fontWeight: maps.typographyWeights.size > 0,
  };

  const report: ComponentReportItem[] = [];
  const canons = dedupe(detected, report);

  const units: Unit[] = [];
  for (const comp of canons) {
    report.push({ type: 'emitted', component: comp.name });
    const unit = buildUnit(comp, maps);
    units.push(unit);
    if (unit.unmapped.length > 0) {
      report.push({ type: 'unmapped', component: comp.name, values: unit.unmapped });
    }
  }

  const tokenSource = opts.tokensImport ?? './tokens';
  const files: Record<string, string> = { ...primitives.files };
  if (units.length > 0) {
    files['components.tsx'] = buildComponentsSource(units, available, tokenSource);
  }

  return { files, report };
}

interface TokenMaps {
  colors: Map<string, string>;
  spacing: Map<string, string>;
  typographySizes: Map<string, string>;
  typographyWeights: Map<string, string>;
}

function buildTokenMaps(proposals: TokenProposal[]): TokenMaps {
  const colors = new Map<string, string>();
  const spacing = new Map<string, string>();
  const typographySizes = new Map<string, string>();
  const typographyWeights = new Map<string, string>();

  for (const proposal of proposals) {
    const canonical = proposal.cluster.canonical;
    if (proposal.cluster.type === 'color') {
      colors.set(canonical, proposal.tokenName);
    } else if (proposal.cluster.type === 'spacing') {
      spacing.set(canonical, proposal.tokenName);
    } else if (proposal.cluster.type === 'typography') {
      if (/(?:px|rem|em)$/.test(canonical)) typographySizes.set(canonical, proposal.tokenName);
      else typographyWeights.set(canonical, proposal.tokenName);
    }
  }

  return { colors, spacing, typographySizes, typographyWeights };
}

// Every style value a component uses on its root element is a candidate
// token slot. Which token group (if any) a CSS property maps to decides
// whether it becomes a constrained prop: colors/spacing/fontSize/fontWeight
// are tokenized by the pipeline; radius/shadows/other props stay literal.
function tokenKindOf(cssProperty: string): SlotKind {
  if (COLOR_PROPS.has(cssProperty)) return 'color';
  if (SPACING_PROPS.has(cssProperty)) return 'spacing';
  if (cssProperty === 'fontSize') return 'fontSize';
  if (cssProperty === 'fontWeight') return 'fontWeight';
  return null;
}

function signature(comp: DetectedComponent): string {
  return `${comp.rootTag.toLowerCase()}|${comp.elements.join('|')}`;
}

function similarName(a: string, b: string): boolean {
  if (a === b) return false;
  const normalize = (s: string) =>
    s.replace(/([a-z])([A-Z])/g, '$1 $2').toLowerCase().split(/\s+/);
  const partsA = normalize(a);
  const partsB = normalize(b);
  const shared = partsA.filter(p => partsB.includes(p));
  const union = new Set([...partsA, ...partsB]).size;
  return shared.length / union >= 0.5;
}

// Merge near-duplicates (drift candidates) into a single canonical, so the
// library emits one constrained component per distinct component, not one per
// accidental copy.
function dedupe(detected: DetectedComponent[], report: ComponentReportItem[]): DetectedComponent[] {
  const result: DetectedComponent[] = [];
  const used = new Set<DetectedComponent>();

  for (const comp of detected) {
    if (used.has(comp)) continue;
    used.add(comp);
    const duplicates = detected.filter(
      other =>
        other !== comp &&
        !used.has(other) &&
        other.rootTag.toLowerCase() === comp.rootTag.toLowerCase() &&
        (signature(other) === signature(comp) || similarName(other.name, comp.name))
    );
    if (duplicates.length === 0) {
      result.push(comp);
      continue;
    }
    for (const dup of duplicates) used.add(dup);
    const canonical = [comp, ...duplicates].sort((a, b) => b.styleValues.length - a.styleValues.length)[0];
    result.push(canonical);
    for (const dup of duplicates) report.push({ type: 'merged', component: dup.name, into: canonical.name });
  }

  return result;
}

function buildUnit(comp: DetectedComponent, maps: TokenMaps): Unit {
  const defaults: Record<string, string | string[]> = {};
  const look: Record<string, string | number> = {};
  const tokenized = new Set<string>();
  const unmapped: string[] = [];

  for (const sv of comp.styleValues) {
    const kind = tokenKindOf(sv.cssProperty);
    if (kind === null) {
      look[sv.cssProperty] = literalValue(sv.cssProperty, sv.rawValue);
      continue;
    }

    const mapped = mapValue(kind, sv.cssProperty, sv.rawValue, maps);
    if (mapped !== null) {
      defaults[sv.cssProperty] = mapped;
      tokenized.add(sv.cssProperty);
    } else {
      unmapped.push(sv.rawValue);
      look[sv.cssProperty] = literalValue(sv.cssProperty, sv.rawValue);
    }
  }

  return {
    name: comp.name,
    element: comp.rootTag,
    rootAttrs: comp.rootAttrs,
    voidElement: comp.voidElement || VOID_ELEMENTS.has(comp.rootTag.toLowerCase()),
    childrenSource: comp.childrenSource,
    defaults,
    look,
    unmapped,
  };
}

function mapValue(kind: Exclude<SlotKind, null>, cssProperty: string, raw: string, maps: TokenMaps): string | string[] | null {
  if (kind === 'color') {
    // Compound values (e.g. "1px solid #e4e4e7", "0 1px 3px rgba(0,0,0,0.12)")
    // must not collapse to a bare color token — that would drop the width,
    // style, or alpha. Only map pure color literals.
    if (!isPureColorLiteral(raw)) return null;
    const canonical = toCanonical(raw);
    if (canonical?.type !== 'color') return null;
    return maps.colors.get(canonical.canonical) ?? null;
  }

  if (kind === 'fontSize') {
    return maps.typographySizes.get(raw.trim()) ?? null;
  }

  if (kind === 'fontWeight') {
    const canonical = toCanonical(raw);
    if (canonical?.type !== 'typography') return null;
    return maps.typographyWeights.get(canonical.canonical) ?? null;
  }

  // spacing: single scale name or a 1–4 token tuple, resolved via resolveSpacing
  const tokens = splitValueTokens(raw);
  if (tokens.length === 0) return null;
  const names: string[] = [];
  for (const token of tokens) {
    const canonical = toCanonical(token.text);
    if (canonical?.type !== 'spacing') return null;
    const name = maps.spacing.get(canonical.canonical);
    if (!name) return null;
    names.push(name);
  }
  if (names.length === 1) return names[0];
  return names;
}

// A color that occupies the entire value — hex, rgb/rgba, hsl/hsla, in all
// numeric notations with optional spaces/commas. Anything else (shorthand
// shorthands, gradients, shadows with offsets) is NOT a pure literal.
function isPureColorLiteral(raw: string): boolean {
  const trimmed = raw.trim().toLowerCase();
  if (/^#[0-9a-f]{3,8}$/.test(trimmed)) return true;
  if (/^rgba?\([0-9., /%]+\)$/.test(trimmed)) return true;
  if (/^hsla?\([0-9., /%]+\)$/.test(trimmed)) return true;
  return false;
}

function literalValue(cssProperty: string, raw: string): string | number {
  if (cssProperty === 'fontWeight' && /^\d+$/.test(raw)) return parseInt(raw, 10);
  return raw;
}

function buildComponentsSource(units: Unit[], available: Available, tokenSource: string): string {
  const parts: string[] = [FILE_HEADER, `import * as React from 'react';`];

  const records: string[] = [];
  if (available.color) records.push('colors');
  if (available.fontSize || available.fontWeight) records.push('typography');
  if (records.length > 0) {
    parts.push(`import { ${records.join(', ')} } from '${tokenSource}';`);
  }

  const primitivesImports: string[] = [];
  if (available.color) primitivesImports.push('ColorName');
  if (available.spacing) {
    primitivesImports.push('Spacing', 'resolveSpacing');
  }
  if (available.fontSize) primitivesImports.push('FontSizeName');
  if (available.fontWeight) primitivesImports.push('FontWeightName');
  parts.push(`import { ${primitivesImports.join(', ')} } from './primitives';`, '');

  for (const unit of units) {
    parts.push(buildComponentSource(unit, available), '');
  }

  return parts.join('\n').replace(/\n+$/, '') + '\n';
}

function buildComponentSource(unit: Unit, available: Available): string {
  const props = unit.defaults;
  const htmlType = htmlAttributesType(unit.element);

  const destructured: string[] = [];
  const resolved: string[] = [];
  const propLines: string[] = [];

  for (const [cssProperty, defaultExpr] of Object.entries(props)) {
    const kind = tokenKindOf(cssProperty);
    if (kind === null) continue;
    const propType = slotType(kind, available);
    if (propType === null) continue;

    propLines.push(`  ${cssProperty}?: ${propType};`);
    destructured.push(`  ${cssProperty} = ${JSON.stringify(defaultExpr)},`);
    resolved.push(`    ...(${cssProperty} !== undefined && { ${cssProperty}: ${resolveExpr(kind, cssProperty)} }),`);
  }

  const hasRawChildren = unit.childrenSource !== null;
  if (!unit.voidElement && !hasRawChildren) destructured.push('  children,');
  destructured.push('  style,', '  ...rest');

  const lookEntries = Object.entries(unit.look)
    .map(([key, value]) => `    ${key}: ${JSON.stringify(value)},`)
    .join('\n');
  const lookBlock = lookEntries.length > 0 ? `const LOOK: React.CSSProperties = {\n${lookEntries}\n  };\n\n  ` : '';

  const attrs = Object.entries(unit.rootAttrs)
    .map(([k, v]) => `${k}${v === 'true' ? '' : `="${v}"`}`)
    .join(' ');
  const attrString = attrs.length > 0 ? `${attrs} ` : '';

  let body: string;
  if (unit.voidElement) {
    body = `  return (\n    <${unit.element} ${attrString}{...rest} style={{ ...LOOK, ...style, ...resolved }} />\n  );`;
  } else if (hasRawChildren) {
    body = `  return (\n    <${unit.element} ${attrString}{...rest} style={{ ...LOOK, ...style, ...resolved }}>\n${unit.childrenSource}\n    </${unit.element}>\n  );`;
  } else {
    body = `  return (\n    <${unit.element} ${attrString}{...rest} style={{ ...LOOK, ...style, ...resolved }}>\n      {children}\n    </${unit.element}>\n  );`;
  }

  return `export type ${unit.name}Props = {\n${propLines.join('\n')}\n} & ${htmlType};

export function ${unit.name}({
${destructured.join('\n')}
}: ${unit.name}Props) {
  ${lookBlock}const resolved: React.CSSProperties = {
${resolved.join('\n')}
  };
${body}
}`;
}

function slotType(kind: Exclude<SlotKind, null>, available: Available): string | null {
  if (kind === 'color') return available.color ? 'ColorName' : null;
  if (kind === 'spacing') return available.spacing ? SPACING_TUPLE_TYPE : null;
  if (kind === 'fontSize') return available.fontSize ? 'FontSizeName' : null;
  if (kind === 'fontWeight') return available.fontWeight ? 'FontWeightName' : null;
  return null;
}

function resolveExpr(kind: Exclude<SlotKind, null>, cssProperty: string): string {
  if (kind === 'spacing') return `resolveSpacing(${cssProperty})`;
  if (kind === 'fontSize' || kind === 'fontWeight') return `typography[${cssProperty}]`;
  return `colors[${cssProperty}]`;
}

function htmlAttributesType(element: string): string {
  if (element === 'input') return 'React.InputHTMLAttributes<HTMLInputElement>';
  if (element === 'select') return 'React.SelectHTMLAttributes<HTMLSelectElement>';
  if (element === 'button') return 'React.ButtonHTMLAttributes<HTMLButtonElement>';
  if (element === 'textarea') return 'React.TextareaHTMLAttributes<HTMLTextAreaElement>';
  if (element === 'svg') return 'React.SVGProps<SVGSVGElement>';
  return 'React.HTMLAttributes<HTMLElement>';
}