import { TokenProposal } from '../pipeline/decision';
import { toCanonical } from '../pipeline/normalizer';
import { splitValueTokens } from '../pipeline/valueTokenizer';
import { compilePrimitives } from '../primitives/compiler';
import { DetectedComponent } from './detector';
import {
  CATALOG_ORDER,
  ArchetypeId,
  TokenSlot,
  archetypeById,
  classifyComponent,
} from './archetypes';

export interface ComponentsResult {
  files: Record<string, string>;
  report: ComponentReportItem[];
}

export type ComponentReportItem =
  | { type: 'matched'; component: string; archetype: ArchetypeId }
  | { type: 'merged'; component: string; into: string }
  | { type: 'unmatched'; component: string; file: string }
  | { type: 'forced'; archetype: ArchetypeId }
  | { type: 'unmapped'; component: string; values: string[] };

export interface ComponentCompilerOptions {
  tokensImport?: string;
  // Explicit selection from config `components`. When set, only these
  // archetypes are emitted (matched ones keep detected defaults, the rest are
  // forced in as generic constrained components).
  include?: ArchetypeId[];
}

const FILE_HEADER = `// Auto-generated by remediation
// Run \`remediation components\` to regenerate
//
// A token-constrained component library compiled from the detected components.
// Component props accept token names only (imported from ./primitives), so
// off-system values (e.g. <Button padding="17px" />) fail to typecheck.
`;

type SlotKind = 'color' | 'spacing' | 'fontSize' | 'fontWeight' | null;

interface Unit {
  archetype: ArchetypeId;
  name: string;
  detected?: DetectedComponent;
  defaults: Partial<Record<TokenSlot, string | string[]>>;
  look: Record<string, string | number>;
  unmapped: string[];
}

interface Available {
  color: boolean;
  spacing: boolean;
  fontSize: boolean;
  fontWeight: boolean;
}

const SLOT_KIND: Record<TokenSlot, SlotKind> = {
  backgroundColor: 'color',
  borderColor: 'color',
  color: 'color',
  padding: 'spacing',
  margin: 'spacing',
  gap: 'spacing',
  fontSize: 'fontSize',
  fontWeight: 'fontWeight',
};

const CSS_PROP: Record<TokenSlot, string> = {
  backgroundColor: 'backgroundColor',
  borderColor: 'borderColor',
  color: 'color',
  padding: 'padding',
  margin: 'margin',
  gap: 'gap',
  fontSize: 'fontSize',
  fontWeight: 'fontWeight',
};

export function compileComponents(
  proposals: TokenProposal[],
  detected: DetectedComponent[],
  opts: ComponentCompilerOptions = {}
): ComponentsResult {
  const primitives = compilePrimitives(proposals, { tokensImport: opts.tokensImport });
  if (Object.keys(primitives.files).length === 0) {
    return { files: {}, report: [] };
  }

  const maps = buildTokenMaps(proposals);
  const available = {
    color: maps.colors.size > 0,
    spacing: maps.spacing.size > 0,
    fontSize: maps.typographySizes.size > 0,
    fontWeight: maps.typographyWeights.size > 0,
  };

  const report: ComponentReportItem[] = [];
  const groups = groupByArchetype(detected, report);
  const matchedIds = new Set(groups.keys());
  const requested = opts.include && opts.include.length > 0 ? opts.include : [...matchedIds];
  const emittedIds = requested.filter(id => CATALOG_ORDER.includes(id));

  const units: Unit[] = [];
  for (const id of emittedIds) {
    const archetype = archetypeById(id);
    const comps = groups.get(id) || [];
    if (comps.length === 0) {
      report.push({ type: 'forced', archetype: id });
      units.push({ archetype: id, name: archetype.componentName, defaults: {}, look: {}, unmapped: [] });
      continue;
    }
    for (const comp of comps) {
      report.push({ type: 'matched', component: comp.name, archetype: id });
      const unit = buildUnit(archetype, comp, maps);
      units.push(unit);
      if (unit.unmapped.length > 0) {
        report.push({ type: 'unmapped', component: comp.name, values: unit.unmapped });
      }
    }
  }

  const source = opts.tokensImport ?? './tokens';
  const built = buildComponentsSource(units, available, source);
  const files: Record<string, string> = { ...primitives.files };
  if (units.length > 0) {
    files['components.tsx'] = built;
  }

  return { files, report };
}

interface TokenMaps {
  colors: Map<string, string>;
  spacing: Map<string, string>;
  typographySizes: Map<string, string>;
  typographyWeights: Map<string, string>;
}

function buildTokenMaps(proposals: TokenProposal[]): TokenMaps {
  const colors = new Map<string, string>();
  const spacing = new Map<string, string>();
  const typographySizes = new Map<string, string>();
  const typographyWeights = new Map<string, string>();

  for (const proposal of proposals) {
    const canonical = proposal.cluster.canonical;
    if (proposal.cluster.type === 'color') {
      colors.set(canonical, proposal.tokenName);
    } else if (proposal.cluster.type === 'spacing') {
      spacing.set(canonical, proposal.tokenName);
    } else if (proposal.cluster.type === 'typography') {
      if (/(?:px|rem|em)$/.test(canonical)) typographySizes.set(canonical, proposal.tokenName);
      else typographyWeights.set(canonical, proposal.tokenName);
    }
  }

  return { colors, spacing, typographySizes, typographyWeights };
}

function groupByArchetype(
  detected: DetectedComponent[],
  report: ComponentReportItem[]
): Map<ArchetypeId, DetectedComponent[]> {
  const byArchetype = new Map<ArchetypeId, DetectedComponent[]>();

  for (const comp of detected) {
    const id = classifyComponent(comp);
    if (!id) {
      report.push({ type: 'unmatched', component: comp.name, file: comp.file });
      continue;
    }
    const list = byArchetype.get(id) || [];
    list.push(comp);
    byArchetype.set(id, list);
  }

  // Merge near-duplicates within an archetype (drift candidates) into a single
  // canonical, so the library emits one constrained component per look.
  const merged = new Map<ArchetypeId, DetectedComponent[]>();
  for (const [id, comps] of byArchetype) {
    merged.set(id, dedupeForArchetype(id, comps, report));
  }

  return merged;
}

function signature(comp: DetectedComponent): string {
  return `${comp.rootTag.toLowerCase()}|${comp.elements.join('|')}`;
}

function similarName(a: string, b: string): boolean {
  if (a === b) return false;
  const normalize = (s: string) =>
    s.replace(/([a-z])([A-Z])/g, '$1 $2').toLowerCase().split(/\s+/);
  const partsA = normalize(a);
  const partsB = normalize(b);
  const shared = partsA.filter(p => partsB.includes(p));
  const union = new Set([...partsA, ...partsB]).size;
  return shared.length / union >= 0.5;
}

function dedupeForArchetype(
  id: ArchetypeId,
  comps: DetectedComponent[],
  report: ComponentReportItem[]
): DetectedComponent[] {
  const result: DetectedComponent[] = [];
  const used = new Set<DetectedComponent>();

  for (const comp of comps) {
    if (used.has(comp)) continue;
    used.add(comp);
    const duplicates = comps.filter(other => other !== comp && !used.has(other) && (signature(other) === signature(comp) || similarName(other.name, comp.name)));
    if (duplicates.length === 0) {
      result.push(comp);
      continue;
    }
    for (const dup of duplicates) used.add(dup);
    const canonical = [comp, ...duplicates].sort((a, b) => b.styleValues.length - a.styleValues.length)[0];
    result.push(canonical);
    for (const dup of duplicates) report.push({ type: 'merged', component: dup.name, into: canonical.name });
  }

  return result;
}

function buildUnit(
  archetype: ReturnType<typeof archetypeById>,
  comp: DetectedComponent,
  maps: TokenMaps
): Unit {
  const defaults: Partial<Record<TokenSlot, string | string[]>> = {};
  const look: Record<string, string | number> = {};
  const tokenized = new Set<string>();
  const unmapped: string[] = [];

  for (const slot of archetype.slots) {
    const value = comp.styleValues.find(sv => sv.cssProperty === slot)?.rawValue;
    if (value === undefined) continue;

    const mapped = mapSlotValue(slot, value, maps);
    if (mapped !== null) {
      defaults[slot] = mapped;
      tokenized.add(slot);
    } else {
      unmapped.push(value);
    }
  }

  for (const sv of comp.styleValues) {
    if (tokenized.has(sv.cssProperty)) continue;
    look[sv.cssProperty] = literalValue(sv.cssProperty, sv.rawValue);
  }

  return { archetype: archetype.id, name: comp.name, detected: comp, defaults, look, unmapped };
}

function mapSlotValue(slot: TokenSlot, raw: string, maps: TokenMaps): string | string[] | null {
  const kind = SLOT_KIND[slot];

  if (kind === 'color') {
    const canonical = toCanonical(raw);
    if (canonical?.type !== 'color') return null;
    return maps.colors.get(canonical.canonical) ?? null;
  }

  if (kind === 'fontSize') {
    const value = raw.trim();
    return maps.typographySizes.get(value) ?? null;
  }

  if (kind === 'fontWeight') {
    const canonical = toCanonical(raw);
    if (canonical?.type !== 'typography') return null;
    return maps.typographyWeights.get(canonical.canonical) ?? null;
  }

  // spacing: single scale name or a 1–4 token tuple
  const tokens = splitValueTokens(raw);
  if (tokens.length === 0) return null;
  const names: string[] = [];
  for (const token of tokens) {
    const canonical = toCanonical(token.text);
    if (canonical?.type !== 'spacing') return null;
    const name = maps.spacing.get(canonical.canonical);
    if (!name) return null;
    names.push(name);
  }
  if (names.length === 1) return names[0];
  return names;
}

function literalValue(cssProperty: string, raw: string): string | number {
  if (cssProperty === 'fontWeight' && /^\d+$/.test(raw)) return parseInt(raw, 10);
  return raw;
}

function buildComponentsSource(units: Unit[], available: Available, tokenSource: string): string {
  const parts: string[] = [FILE_HEADER, `import * as React from 'react';`];

  const records: string[] = [];
  if (available.color) records.push('colors');
  if (available.fontSize || available.fontWeight) records.push('typography');
  if (records.length > 0) {
    parts.push(`import { ${records.join(', ')} } from '${tokenSource}';`);
  }

  const primitivesImports: string[] = [];
  if (available.color) primitivesImports.push('ColorName');
  if (available.spacing) {
    primitivesImports.push('Spacing', 'resolveSpacing');
  }
  if (available.fontSize) primitivesImports.push('FontSizeName');
  if (available.fontWeight) primitivesImports.push('FontWeightName');
  parts.push(`import { ${primitivesImports.join(', ')} } from './primitives';`, '');

  for (const unit of units) {
    parts.push(buildComponentSource(unit, available), '');
  }

  return parts.join('\n').replace(/\n+$/, '') + '\n';
}

function buildComponentSource(unit: Unit, available: Available): string {
  const archetype = archetypeById(unit.archetype);
  const element = archetype.element;
  const htmlType = htmlAttributesType(element, archetype.voidElement);
  const props = slotProperties(archetype, available);

  const destructured: string[] = [];
  const resolved: string[] = [];
  for (const slot of archetype.slots) {
    const propType = slotType(slot, available);
    if (!propType) continue;

    const defaultExpr = unit.defaults[slot];
    const decl = defaultExpr !== undefined ? `  ${slot} = ${JSON.stringify(defaultExpr)},` : `  ${slot},`;
    destructured.push(decl);

    resolved.push(`    ...(${slot} !== undefined && { ${CSS_PROP[slot]}: ${resolveExpr(slot)} }),`);
  }

  if (!archetype.voidElement) destructured.push('  children,');
  destructured.push('  style,', '  ...rest');

  const lookEntries = Object.entries(unit.look)
    .map(([key, value]) => `    ${key}: ${JSON.stringify(value)},`)
    .join('\n');
  const lookBlock = lookEntries.length > 0 ? `const LOOK: React.CSSProperties = {\n${lookEntries}\n  };\n\n  ` : '';

  const attrs = archetype.elementAttrs
    ? Object.entries(archetype.elementAttrs).map(([k, v]) => `${k}${v === 'true' ? '' : `="${v}"`}`).join(' ')
    : '';
  const attrString = attrs.length > 0 ? `${attrs} ` : '';

  const body =
    archetype.voidElement
      ? `  return (\n    <${element} ${attrString}{...rest} style={{ ...LOOK, ...style, ...resolved }} />\n  );`
      : `  return (\n    <${element} ${attrString}{...rest} style={{ ...LOOK, ...style, ...resolved }}>\n      {children}\n    </${element}>\n  );`;

  return `export type ${unit.name}Props = {\n${props.join('\n')}\n} & ${htmlType};

export function ${unit.name}({
${destructured.join('\n')}
}: ${unit.name}Props) {
  ${lookBlock}const resolved: React.CSSProperties = {
${resolved.join('\n')}
  };
${body}
}`;
}

function slotProperties(archetype: ReturnType<typeof archetypeById>, available: Available): string[] {
  const props: string[] = [];
  for (const slot of archetype.slots) {
    const propType = slotType(slot, available);
    if (!propType) continue;
    props.push(`  ${slot}?: ${propType};`);
  }
  return props;
}

function slotType(slot: TokenSlot, available: Available): string | null {
  const kind = SLOT_KIND[slot];
  if (kind === 'color') return available.color ? 'ColorName' : null;
  if (kind === 'spacing') {
    return available.spacing
      ? 'Spacing | [Spacing, Spacing] | [Spacing, Spacing, Spacing] | [Spacing, Spacing, Spacing, Spacing]'
      : null;
  }
  if (kind === 'fontSize') return available.fontSize ? 'FontSizeName' : null;
  if (kind === 'fontWeight') return available.fontWeight ? 'FontWeightName' : null;
  return null;
}

function resolveExpr(slot: TokenSlot): string {
  const kind = SLOT_KIND[slot];
  if (kind === 'spacing') return `resolveSpacing(${slot})`;
  if (kind === 'fontSize' || kind === 'fontWeight') return `typography[${slot}]`;
  return `colors[${slot}]`;
}

function htmlAttributesType(element: string, voidElement?: boolean): string {
  if (element === 'input') return 'React.InputHTMLAttributes<HTMLInputElement>';
  if (element === 'select') return 'React.SelectHTMLAttributes<HTMLSelectElement>';
  if (element === 'button') return 'React.ButtonHTMLAttributes<HTMLButtonElement>';
  return 'React.HTMLAttributes<HTMLElement>';
}